// Generated by CoffeeScript 1.3.3
(function() {
  var coffee, coffee_args, fs, glob, path, spawn, yamljs;

  coffee = require('coffee-script');

  fs = require('fs');

  glob = require('glob');

  path = require('path');

  spawn = require('child_process').spawn;

  yamljs = require('yaml-js');

  coffee_args = [path.join(path.dirname(require.resolve('coffee-script')), '..', '..', 'bin', 'coffee'), '--output', '.', '--compile', 'src'];

  task('build', 'Builds the project', function() {
    invoke('build:coffee');
    return invoke('build:yaml');
  });

  task('build:coffee', 'Builds all CoffeeScript files under src', function() {
    return spawn(process.execPath, coffee_args, {
      customFds: [0, 1, 2]
    });
  });

  task('build:yaml', 'Builds all YAML files under src', function() {
    return glob('src/{*.,**/*.}{yaml,yml}', function(err, files) {
      var file, yaml, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        yaml = file.replace(/^src\//, '').replace(/ya?ml$/, 'json');
        _results.push(fs.writeFileSync(yaml, JSON.stringify(yamljs.load(fs.readFileSync(file)), null, '  ')));
      }
      return _results;
    });
  });

}).call(this);
