// Generated by CoffeeScript 1.3.3
(function() {
  var chai, mocha_args, path, spawn;

  chai = require('chai');

  path = require('path');

  spawn = require('child_process').spawn;

  mocha_args = [path.join(path.dirname(require.resolve('mocha')), 'bin', 'mocha'), '-R', 'spec', '--recursive', '--require', 'coffee-script', '--require', path.join(__dirname, '..', 'test', 'support', 'test_helper'), '--compilers', 'coffee:coffee-script'];

  task('test', 'Runs the project\'s tests on the source', function() {
    return spawn(process.execPath, mocha_args, {
      customFds: [0, 1, 2]
    });
  });

  task('test:watch', 'Watches the project\'s source and reruns tests on changes', function() {
    return spawn(process.execPath, mocha_args.concat(['--watch']), {
      customFds: [0, 1, 2]
    });
  });

}).call(this);
