// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(packages) {
    var pkg, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = packages.length; _i < _len; _i++) {
      pkg = packages[_i];
      _results.push(require("./" + pkg));
    }
    return _results;
  };

}).call(this);
