name:             plantation
version:          0.0.13
main:             ./lib/plantation
bin:
  plantation:     ./bin/plantation
dependencies:
  colors:         ~1
  watch:          0.16.0
  semver:         ~4
peerDependencies: &peerDependencies
  coffee-script:  ~1
  chai:           ~2
  mocha:          ~2
  sinon:          ~1
  sinon-chai:     ~2
  yaml-js:        0.1.1
devDependencies:  *peerDependencies