name:            plantation
version:         0.0.8
main:            ./lib/plantation
bin:
  plantation:    ./bin/plantation
dependencies:
  coffee-script: 1.x.x
  chai:          1.x.x
  mocha:         1.x.x
  node-watch:    0.3.x
  sinon:         1.x.x
  sinon-chai:    2.x.x
  sty:           0.6.x
  yaml-js:       0.0.7