name:             plantation
version:          0.0.17
main:             ./lib/plantation
bin:
  plantation:     ./bin/plantation
repository:
  type:           git
  url:            https://github.com/connec/plantation.git
dependencies:
  colors:         ~1
  node-watch:     0.3.4
  semver:         ~4
peerDependencies:
  coffeescript:   '*'
  chai:           '*'
  mocha:          '*'
  sinon:          '*'
  sinon-chai:     '*'
  yaml-js:        '*'
devDependencies:
  coffeescript:   ~2.1.0
  yaml-js:        0.2.0
